import type { IUser } from '@/types/types';
// import type { TeachSkill } from '@/widgets/Card/types';

// Добавим photos в TeachSkill для similarUsers

export const mockUser: IUser = {
  id: 1,
  liked: 1,
  avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Jameson&backgroundColor=b6e3f4',
  name: 'Александр',
  city: 'Москва',
  age: 30,
  dateOfBirth: '22-03-1995',
  gender: 'мужской',
  email: 'alexander95@email.com',
  password: 'aB3kL9mNpQ7rS2tU',
  createdAt: '2022-06-14',
  about:
    'Привет! Увлекаюсь проектным управлением и всегда рад поделиться опытом — особенно если речь о том, как не сгореть на работе.',
  card_people: {
    skill: 'Проектное управление',
    category: 'Бизнес и карьера',
    subcategory: 'Проектное управление',
    description:
      'Работаю в IT-проектах уже 6 лет и прошёл путь от аналитика до руководителя. Научу ставить реалистичные дедлайны, распределять задачи без перегруза команды и использовать методологии вроде Scrum или Kanban так, чтобы они работали, а не мешали. Покажу, как вести документацию, которая действительно помогает, а не лежит мёртвым грузом.',
    photos: [
      'https://c.pxhere.com/photos/46/93/white_board_startup_start_up_presentation_board_diagram_present_show-764635.jpg!d',
      'https://c.pxhere.com/photos/e5/16/code_data_programming_code_computer_programming_information_technology_technology_security_development-693080.jpg!d',
      'https://c.pxhere.com/photos/53/20/digital_marketing_emarketing_the_positioning_of_the_seo_sem_serp_google_business-450236.jpg!d',
      'https://c.pxhere.com/photos/58/a3/hourglass_clock_time_deadline_hour_rush_hurry_minute-484055.jpg!d',
    ],
  },
  skill_off: ['Проектное управление', 'Личный бренд', 'Предпринимательство', 'Управление командой'],
};

export const similarUsers: IUser[] = [
  {
    id: 2,
    liked: 2,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Mackenzie&backgroundColor=b6e3f4',
    name: 'Анна',
    city: 'Санкт-Петербург',
    age: 28,
    about:
      'Люблю учиться новому, особенно если это можно делать за чаем и в пижаме. Всегда готова пообщаться и обменяться чем-то интересным.',
    card_people: {
      skill: 'Личностное развитие',
      category: 'Образование и развитие',
      subcategory: 'Личностное развитие',
      description:
        'Я верю, что рост начинается с маленьких шагов — и сама каждый день пробую что-то новое. Поделюсь практиками осознанности, техниками постановки целей и способами находить мотивацию даже в сложные дни. Помогу разобраться в своих ценностях и начать жить в согласии с ними, а не по чужим ожиданиям.',
      photos: [
        'https://c.pxhere.com/photos/ff/c2/ux_prototyping_design_webdesign_app_mobile_business_interface-723648.jpg!d',
        'https://c.pxhere.com/photos/08/0a/flower_life_crack_desert_drought_survival_loneliness_one-865929.jpg!d',
        'https://c.pxhere.com/photos/af/67/startup_business_businessman_notebook_laptop_computer_company_office-914296.jpg!d',
        'https://c.pxhere.com/photos/84/a1/cactus_eyes_book_pot_reading_education_study_schoolboy-672564.jpg!d',
      ],
    },
    skill_off: ['Личностное развитие', 'Коучинг', 'Ментальное здоровье', 'Навыки преподавания'],
    dateOfBirth: '05-11-1997',
    gender: 'женский',
    email: 'anna97@email.com',
    password: 'Xy8vW4cRnM6bZ1qE',
    createdAt: '2022-09-03',
  },
  {
    id: 3,
    liked: 3,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Aidan&backgroundColor=b6e3f4',
    name: 'Дмитрий',
    city: 'Новосибирск',
    age: 27,
    about:
      'Фотографирую всё подряд — от закатов до кофе в кружке. Готов научить основам композиции).',
    card_people: {
      skill: 'Фотография',
      category: 'Творчество и искусство',
      subcategory: 'Фотография',
      description:
        'Снимаю больше 5 лет — от уличной фотографии до портретов друзей. Научу видеть свет, выстраивать кадр по правилам (и когда их можно нарушать), работать с композицией и цветом. Покажу, как делать сильные фото даже на смартфон, и поделюсь базовыми приёмами в Lightroom для быстрой и красивой обработки.',
      photos: [
        'https://c.pxhere.com/photos/9c/e6/camera_photography_vintage_photographer_antique-72.jpg!d',
        'https://c.pxhere.com/photos/e2/2b/track_photographer_railway_person_walk_away-38140.jpg!d',
        'https://c.pxhere.com/photos/b7/5e/photography_camera_photographer_digital_camera_dslr-99202.jpg!d',
        'https://c.pxhere.com/photos/65/09/photographer_hand_man_holding_len-32792.jpg!d',
      ],
    },
    skill_off: ['Фотография', 'Видеомонтаж', 'Рисование и иллюстрация', 'Музыка и звук'],
    dateOfBirth: '17-08-1998',
    gender: 'мужской',
    email: 'dmitry98@email.com',
    password: 'Kj5hG2fD9sA7wP3L',
    createdAt: '2023-01-28',
  },
  {
    id: 4,
    liked: 4,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Jessica&backgroundColor=b6e3f4',
    name: 'Екатерина',
    city: 'Екатеринбург',
    age: 23,
    about:
      'Мне 23, и я только начинаю разбираться в английском. Готова помочь с рисованием или йогой!',
    card_people: {
      skill: 'Рисование и иллюстрация',
      category: 'Творчество и искусство',
      subcategory: 'Рисование и иллюстрация',
      description:
        'Рисую с детства и сейчас веду мини-курсы для начинающих. Покажу, как преодолеть страх чистого листа, освоить базовые приёмы акварели и создавать простые, но выразительные зарисовки. Научу видеть формы и тени, работать с композицией и превращать обычные моменты в маленькие произведения искусства.',
      photos: [
        'https://c.pxhere.com/photos/27/31/kids_girl_pencil_drawing_notebook_study_vdvoem_friends-837883.jpg!d',
        'https://c.pxhere.com/photos/f5/60/pencil_crayon_colored_several_colors_wooden_natural_drawing-893050.jpg!d',
        'https://c.pxhere.com/photos/d2/8e/charcoal_drawing_charcoal_pencil_portrait_profile_man_face_head_human-558649.jpg!d',
        'https://c.pxhere.com/photos/f5/2a/hand_hand_drawing_drawing_sketch_design_symbol_drawn_pencil-1379092.jpg!d',
      ],
    },
    skill_off: ['Рисование и иллюстрация', 'Арт-терапия', 'Декор и DIY', 'Креативное письмо'],
    dateOfBirth: '12-04-2002',
    gender: 'женский',
    email: 'ekaterina02@email.com',
    password: 'Qw9eR8tY4uI6oP1a',
    createdAt: '2022-11-17',
  },
  {
    id: 5,
    liked: 5,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Adrian&backgroundColor=b6e3f4',
    name: 'Сергей',
    city: 'Казань',
    age: 42,
    about:
      'Опытный предприниматель, но до сих пор учусь слушать. Могу подсказать, как выстроить личный бренд.',
    card_people: {
      skill: 'Личный бренд',
      category: 'Бизнес и карьера',
      subcategory: 'Личный бренд',
      description:
        'За 15 лет в бизнесе я запускал несколько проектов и понял: люди покупают не продукт, а доверие к человеку. Поделюсь, как выстроить узнаваемый образ в соцсетях, говорить на своём языке и привлекать клиентов без агрессивного маркетинга. Помогу определить вашу уникальную ценность и показать её миру — без фальши и шаблонов.',
      photos: [
        'https://c.pxhere.com/photos/b0/2d/student_typing_keyboard_text_woman_startup_business_people-871986.jpg!d',
        'https://c.pxhere.com/photos/e3/64/notebook_workplace_desk_iphone_library_study_studying_learning-971381.jpg!d',
        'https://c.pxhere.com/photos/ce/aa/keyboard_coffee_watch_notebook_hand-36717.jpg!d',
        'https://c.pxhere.com/photos/7a/9e/socialmedia_facebook_twitter_network_instagram_marketing_online-858156.jpg!d',
      ],
    },
    skill_off: [
      'Личный бренд',
      'Предпринимательство',
      'Продажи и переговоры',
      'Управление командой',
    ],
    dateOfBirth: '01-12-1983',
    gender: 'мужской',
    email: 'sergey83@email.com',
    password: 'Mz3xC7vB2nM9kL4s',
    createdAt: '2022-04-22',
  },
  // ДОБАВЛЯЕМ ЕЩЁ 3 ПОЛЬЗОВАТЕЛЯ
  {
    id: 6,
    liked: 6,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Valentina&backgroundColor=b6e3f4',
    name: 'Ольга',
    city: 'Нижний Новгород',
    age: 40,
    about: 'Обожаю готовить — от борща до суши. Если хотите научиться - приходите!',
    card_people: {
      skill: 'Приготовление еды',
      category: 'Дом и уют',
      subcategory: 'Приготовление еды',
      description:
        'Готовлю с 16 лет и пробовала всё — от домашней выпечки до японской кухни. Научу готовить вкусно, быстро и без стресса: от базовых соусов до праздничных блюд. Поделюсь лайфхаками по планированию меню, хранению продуктов и тому, как удивлять близких даже в будни.',
      photos: [
        'https://c.pxhere.com/photos/ca/d2/olive_oil_salad_dressing_cooking_olive_healthy_vegetarian_food_diet-853081.jpg!d',
        'https://c.pxhere.com/photos/88/be/woman_kitchen_man_everyday_life_blond_brunette_board_vegetables-1281998.jpg!d',
        'https://c.pxhere.com/photos/42/30/slimming_cleaning_dish_stew_eating_meal_food_kitchen-1283880.jpg!d',
        'https://c.pxhere.com/photos/f8/6f/food_eat_waffle_breakfast_gathering-4389.jpg!d',
      ],
    },
    skill_off: ['Приготовление еды', 'Домашние финансы', 'Уборка и организация', 'Питание и ЗОЖ'],
    dateOfBirth: '19-07-1985',
    gender: 'женский',
    email: 'olga85@email.com',
    password: 'Tp6oI1uY5tR8eW2q',
    createdAt: '2023-03-09',
  },
  {
    id: 7,
    liked: 7,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Ryan&backgroundColor=b6e3f4',
    name: 'Артём',
    city: 'Челябинск',
    age: 25,
    about:
      'Учу тайм-менеджменту (сам только начал осваивать 😅). А ещё могу показать, как делать классные фото на телефон!',
    card_people: {
      skill: 'Тайм-менеджмент',
      category: 'Бизнес и карьера',
      subcategory: 'Тайм-менеджмент',
      description:
        'Я сам недавно вылез из хаоса дедлайнов и теперь делюсь тем, что реально работает. Покажу, как планировать день без выгорания, расставлять приоритеты и использовать метод «помидора» так, чтобы он не надоел через неделю. Научу находить время и на работу, и на отдых — без чувства вины.',
      photos: [
        'https://c.pxhere.com/photos/58/a3/hourglass_clock_time_deadline_hour_rush_hurry_minute-484055.jpg!d',
        'https://c.pxhere.com/photos/bc/5c/time_clock_movement_motion_time_change_time_travel_minute_hour-551763.jpg!d',
        'https://c.pxhere.com/photos/11/6b/waiting_appointment_schedule_time_hurry_urgent_timetable_watch-948348.jpg!d',
        'https://c.pxhere.com/photos/91/bb/clock_time_hour_alarm_clock_alarm-237.jpg!d',
      ],
    },
    skill_off: ['Тайм-менеджмент', 'Фотография', 'Йога и медитация', 'Осознанность'],
    dateOfBirth: '29-02-2000',
    gender: 'мужской',
    email: 'artem00@email.com',
    password: 'Nm4bV9cX3zL7kJ6h',
    createdAt: '2022-07-31',
  },
  {
    id: 8,
    liked: 8,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Liliana&backgroundColor=b6e3f4',
    name: 'Татьяна',
    city: 'Самара',
    age: 36,
    about: 'Практикую йогу уже 7 лет и с радостью поделюсь базовыми асанами.',
    card_people: {
      skill: 'Йога и медитация',
      category: 'Здоровье и лайфстайл',
      subcategory: 'Йога и медитация',
      description:
        'Занимаюсь хатха-йогой и медитацией с 2017 года и прошла обучение как инструктор. Научу выполнять базовые асаны безопасно, подстроив под ваш уровень гибкости и состояние тела. Поделюсь простыми техниками дыхания и медитации, которые помогут снять тревожность и лучше спать — даже если у вас всего 10 минут в день.',
      photos: [
        'https://c.pxhere.com/photos/a7/36/plank_fitness_muscular_exercising_girl_shape_strong_arms-634799.jpg!d',
        'https://c.pxhere.com/photos/9a/a1/fitness_yoga_healthy_exercise_yoga_woman_pose_woman_body-634798.jpg!d',
        'https://c.pxhere.com/photos/77/bc/silhouette_yoga_person_adult_human-23886.jpg!d',
        'https://c.pxhere.com/photos/20/fc/women_yoga_classes_asana_fitness_instructor_hatha_yoga_professor_posture-826575.jpg!d',
      ],
    },
    skill_off: ['Йога и медитация', 'Ментальное здоровье', 'Личностное развитие', 'Коучинг'],
    dateOfBirth: '30-10-1989',
    gender: 'женский',
    email: 'tatiana89@email.com',
    password: 'Fg7dS2aQ9wE5rT1y',
    createdAt: '2022-12-25',
  },
  {
    id: 9,
    liked: 9,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Leah&backgroundColor=b6e3f4',
    name: 'Максим',
    city: 'Омск',
    age: 33,
    about: 'Занимаюсь продажами и умею отлично готовить пасту — обмен интересен?',
    card_people: {
      skill: 'Продажи и переговоры',
      category: 'Бизнес и карьера',
      subcategory: 'Продажи и переговоры',
      description:
        'Работаю в B2B-продажах более 8 лет и закрыл сотни сделок — от холодных звонков до сложных переговоров с топ-менеджерами. Научу слушать клиента по-настоящему, задавать правильные вопросы и вести диалог так, чтобы решение о покупке пришло само. Поделюсь техниками работы с возражениями и построения долгосрочных отношений.',
      photos: [
        'https://c.pxhere.com/images/19/60/4f2f49bb3104905dcfdee2622452-1442697.jpg!d',
        'https://c.pxhere.com/images/03/9c/6ffa1ef16717d4a2b0a50f2b8e69-1652040.jpg!d',
        'https://c.pxhere.com/images/e0/10/dfb33e33d1a965f3b8482620586d-1652044.jpg!d',
        'https://c.pxhere.com/photos/3a/bc/handshake_hand_give_business_man_giving_offer_cooperation-1187331.jpg!d',
      ],
    },
    skill_off: [
      'Продажи и переговоры',
      'Приготовление еды',
      'Резюме и собеседование',
      'Маркетинг и реклама',
    ],
    dateOfBirth: '14-05-1992',
    gender: 'мужской',
    email: 'maksim92@email.com',
    password: 'Hj8kL3mN6bV4cX9z',
    createdAt: '2023-05-18',
  },
  {
    id: 10,
    liked: 10,
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Christian&backgroundColor=b6e3f4',
    name: 'Наталья',
    city: 'Ростов-на-Дону',
    age: 36,
    about:
      'Работаю в HR и помогу с резюме или подготовкой к собеседованию. А сама хочу научиться ухаживать за домашними растениями — они у меня почему-то чахнут :(',
    card_people: {
      skill: 'Резюме и собеседование',
      category: 'Бизнес и карьера',
      subcategory: 'Резюме и собеседование',
      description:
        'Как HR с 10-летним стажем, я просмотрела тысячи резюме и провела сотни собеседований. Помогу составить резюме, которое пройдёт ATS и зацепит рекрутера, и подготовлю к любому формату интервью — от case-задач до поведенческих вопросов. Научу говорить о себе уверенно, но без пафоса, и находить сильные стороны даже в нестандартном опыте.',
      photos: [
        'https://c.pxhere.com/images/43/16/5d20214868c848d4f2108329aef9-1437771.jpg!d',
        'https://c.pxhere.com/images/9a/0e/807a956089bcb072dcb00005eef4-1578383.jpg!d',
        'https://c.pxhere.com/photos/c8/8f/handshake_business_hand_agreement_communication_contract_cooperation_happiness-583378.jpg!d',
        'https://c.pxhere.com/images/82/8a/fc8055a91dee3a352a02fd7e4920-1440163.jpg!d',
      ],
    },
    skill_off: [
      'Резюме и собеседование',
      'Личностное развитие',
      'Навыки преподавания',
      'Скорочтение',
    ],
    dateOfBirth: '09-01-1994',
    gender: 'женский',
    email: 'natalya94@email.com',
    password: 'Uy2iO7pL4kM9nB5v',
    createdAt: '2022-08-12',
  },
];
