export const LOGIN_TEXTS = {
  title: 'Вход',
  emailTitle: 'Email',
  emailPlaceholder: 'Введите email',
  passwordTitle: 'Пароль',
  passwordPlaceholder: 'Введите ваш пароль',
  loginButton: 'Войти',
  registerLink: 'Зareгистрироваться',
  socialGoogle: 'Продолжить с Google',
  socialApple: 'Продолжить с Apple',
  onboardingTitle: 'С возвращением в SkillSwap!',
  onboardingText: 'Обменивайтесь знаниями и навыками с другими людьми',
  error: {
    requiredEmail: 'Email обязателен',
    requiredPassword: 'Пароль обязателен',
    invalidEmail: 'Некорректный email',
    invalidCredentials: 'Неверный email или пароль',
    minPasswordLength: 'Пароль должен быть не менее 6 символов',
  },
};
